create_driver arduino_driver
set_sw_property hw_class_name DE10_Lite_Arduino_IP
set_sw_property version 1
set_sw_property min_compatible_hw_version 1.0
add_sw_property bsp_subdirectory drivers
add_sw_property include_source HAL/inc/DE10_Lite_Arduino_Driver.h
add_sw_property supported_bsp_type HAL